//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortArticle
    {
        public int Id { get; set; }
        public int IdFull { get; set; }
        public string ShortContent { get; set; }
    }
}
